# Generated by Django 3.2.4 on 2021-10-29 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Institution')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'fundacja'), ('organizacja', 'organizacja pozarządowa'), ('zbiórka lokalna', 'zbiórka lokalna')], default='fundacja', max_length=200, verbose_name='Type')),
                ('categories', models.ManyToManyField(to='main_app.Category', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(default='45-000', max_length=10, verbose_name='Zip code')),
                ('pick_up_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date pick up')),
                ('pick_up_time', models.DateTimeField(verbose_name='Time pick up')),
                ('pick_up_comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('categories', models.ManyToManyField(to='main_app.Category', verbose_name='Categories')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.institution', verbose_name='Institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
